services:
  - type: web
    name: gestion-taches
    runtime: docker
    repo: https://github.com/Mouhinf/gestion_taches.git
    plan: free
    region: oregon
    healthCheckPath: /
    # Exécute les migrations après le premier déploiement réussi
    initialDeployHook: php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-taches-db
          property: connectionString

databases:
  - name: gestion-taches-db
    plan: free
    region: oregon